# Generated by Django 2.2.4 on 2019-09-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resumelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('position2', models.CharField(max_length=200)),
                ('resume_name', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=200)),
                ('born_year', models.CharField(max_length=200)),
                ('final_edu', models.CharField(max_length=200)),
                ('work_year', models.CharField(max_length=200)),
                ('resume_detail', models.TextField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('outcome', models.TextField()),
            ],
        ),
    ]
