# Generated by Django 2.2.4 on 2019-09-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumelist',
            name='outcome',
            field=models.CharField(max_length=200),
        ),
    ]
