# Generated by Django 2.2.4 on 2019-09-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0002_auto_20190907_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumelist',
            name='level',
        ),
        migrations.AddField(
            model_name='resumelist',
            name='position_detail',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumelist',
            name='born_year',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resumelist',
            name='company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resumelist',
            name='final_edu',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resumelist',
            name='outcome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resumelist',
            name='position',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resumelist',
            name='position2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resumelist',
            name='resume_detail',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resumelist',
            name='resume_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resumelist',
            name='sex',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resumelist',
            name='work_year',
            field=models.CharField(max_length=100),
        ),
    ]
