# Generated by Django 2.1.1 on 2019-09-11 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0003_auto_20190907_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumelist',
            name='salary',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
